package com.ilesteban.drools.recursion;

rule "Apply more than 3 years seniority discount" //Case5.java
no-loop true
when
    $c: Customer(seniority > 3)
then
    modify($c){
        setDiscount($c.getDiscount()+0.1),
        addDiscountReason("Seniority grater than 3 years")
    }
end

rule "Apply more than 5 years seniority discount"
no-loop true
when
    $c: Customer(seniority > 5)
then
    modify($c){
        setDiscount($c.getDiscount()+0.1),
        addDiscountReason("Seniority grater than 5 years")
    }
end

