package com.ilesteban.drools.recursion;

rule "Apply more than 3 years seniority discount" //Case8.java
lock-on-active true
when
    $c: Customer(seniority > 3)
then
    modify($c){
        setDiscount($c.getDiscount()+0.1),
        addDiscountReason("Seniority grater than 3 years")
    }
end

rule "Apply more than 5 years seniority discount"
lock-on-active true
when
    $c: Customer(seniority > 5)
then
    modify($c){
        setDiscount($c.getDiscount()+0.1),
        addDiscountReason("Seniority grater than 5 years")
    }
end

rule "Apply more than 3 children discount"
lock-on-active true
when
    $c: Customer(childrenCount > 3)
then
    modify($c){
        setDiscount($c.getDiscount()+0.1),
        addDiscountReason("More than 3 children")
    }
end

rule "No Customer has a discount grater than 25"
lock-on-active true
when
    $c: Customer(discount > 0.25)
then
    modify($c){
        setDiscount(0.25)
    }
end